kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: connect-connect-1
spec:
  storageClassName: connect
  accessModes:
    - ReadWriteOnce
  volumeName: connect1
  resources:
    requests:
      storage: 2Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: connect-connect-2
spec:
  storageClassName: connect
  accessModes:
    - ReadWriteOnce
  volumeName: connect2
  resources:
    requests:
      storage: 2Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: connect-connect-3
spec:
  storageClassName: connect
  accessModes:
    - ReadWriteOnce
  volumeName: connect3
  resources:
    requests:
      storage: 2Gi
apiVersion: v1
kind: Service
metadata:
  name: connect-rest
  labels:
    app: connect
spec:
  ports:
  - port: 8083
  selector:
    app: connect
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: connect
spec:
  selector:
    matchLabels:
      app: connect
  serviceName: "connect-rest"
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: connect
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - connect
              topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: 10
      containers:
      - name: connect
        image: docker.artifactory.company.com/kafka/cp-kafka-connect:3.3.1
        env:
        - name: CONNECT_BOOTSTRAP_SERVERS
          value: "kafka-kafka-headless:9092"
        - name: CONNECT_REST_PORT
          value: "8083"
        - name: CONNECT_GROUP_ID
          value: "quickstart"
        - name: CONNECT_CONFIG_STORAGE_TOPIC
          value: "quickstart-config"
        - name: CONNECT_OFFSET_STORAGE_TOPIC
          value: "quickstart-offsets"
        - name: CONNECT_STATUS_STORAGE_TOPIC
          value: "quickstart-status"
        - name: CONNECT_KEY_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_VALUE_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_INTERNAL_KEY_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_INTERNAL_VALUE_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_REST_ADVERTISED_HOST_NAME
          value: "connect-rest.default.svc.cluster.local"
        - name: CONNECT_LOG4J_LOGGERS
          value: "org.reflections=ERROR"
        - name: CONNECT_PLUGIN_PATH
          value: "/usr/share/java"
        ports:
        - containerPort: 8083
        volumeMounts:
        - name: connect
          mountPath: /kafka/connect
  volumeClaimTemplates:
  - metadata:
      name: connect
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: connect
      resources:
        requests:
          storage: 2Gi
