apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
  - port: 29092
  clusterIP: None
  selector:
    app: kafka
----
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: broker
spec:
  serviceName: "kafka"
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:3.3.1
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:32181"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://broker-0.kafka.svc.cluster.local:29092
        ports:
        - containerPort: 29092
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  ports:
  - port: 32181
  clusterIP: None
  selector:
    app: zookeeper
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  serviceName: "zookeeper"
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:3.3.1
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "32181"
        ports:
        - containerPort: 32181
